INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Afghanistan','AF','AFG',004,'ISO 3166-2:AF');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Åland Islands','AX','ALA',248,'ISO 3166-2:AX');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Albania','AL','ALB',008,'ISO 3166-2:AL');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Algeria','DZ','DZA',012,'ISO 3166-2:DZ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('American Samoa','AS','ASM',016,'ISO 3166-2:AS');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Andorra','AD','AND',020,'ISO 3166-2:AD');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Angola','AO','AGO',024,'ISO 3166-2:AO');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Anguilla','AI','AIA',660,'ISO 3166-2:AI');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Antarctica','AQ','ATA',010,'ISO 3166-2:AQ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Antigua and Barbuda','AG','ATG',028,'ISO 3166-2:AG');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Argentina','AR','ARG',032,'ISO 3166-2:AR');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Armenia','AM','ARM',051,'ISO 3166-2:AM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Aruba','AW','ABW',533,'ISO 3166-2:AW');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Australia','AU','AUS',036,'ISO 3166-2:AU');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Austria','AT','AUT',040,'ISO 3166-2:AT');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Azerbaijan','AZ','AZE',031,'ISO 3166-2:AZ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Bahamas','BS','BHS',044,'ISO 3166-2:BS');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Bahrain','BH','BHR',048,'ISO 3166-2:BH');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Bangladesh','BD','BGD',050,'ISO 3166-2:BD');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Barbados','BB','BRB',052,'ISO 3166-2:BB');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Belarus','BY','BLR',112,'ISO 3166-2:BY');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Belgium','BE','BEL',056,'ISO 3166-2:BE');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Belize','BZ','BLZ',084,'ISO 3166-2:BZ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Benin','BJ','BEN',204,'ISO 3166-2:BJ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Bermuda','BM','BMU',060,'ISO 3166-2:BM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Bhutan','BT','BTN',064,'ISO 3166-2:BT');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Bolivia, Plurinational State of','BO','BOL',068,'ISO 3166-2:BO');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Bosnia and Herzegovina','BA','BIH',070,'ISO 3166-2:BA');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Botswana','BW','BWA',072,'ISO 3166-2:BW');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Bouvet Island','BV','BVT',074,'ISO 3166-2:BV');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Brazil','BR','BRA',076,'ISO 3166-2:BR');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('British Indian Ocean Territory','IO','IOT',086,'ISO 3166-2:IO');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Brunei Darussalam','BN','BRN',096,'ISO 3166-2:BN');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Bulgaria','BG','BGR',100,'ISO 3166-2:BG');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Burkina Faso','BF','BFA',854,'ISO 3166-2:BF');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Burundi','BI','BDI',108,'ISO 3166-2:BI');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Cambodia','KH','KHM',116,'ISO 3166-2:KH');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Cameroon','CM','CMR',120,'ISO 3166-2:CM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Canada','CA','CAN',124,'ISO 3166-2:CA');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Cape Verde','CV','CPV',132,'ISO 3166-2:CV');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Cayman Islands','KY','CYM',136,'ISO 3166-2:KY');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Central African Republic','CF','CAF',140,'ISO 3166-2:CF');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Chad','TD','TCD',148,'ISO 3166-2:TD');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Chile','CL','CHL',152,'ISO 3166-2:CL');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('China','CN','CHN',156,'ISO 3166-2:CN');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Christmas Island','CX','CXR',162,'ISO 3166-2:CX');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Cocos (Keeling) Islands','CC','CCK',166,'ISO 3166-2:CC');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Colombia','CO','COL',170,'ISO 3166-2:CO');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Comoros','KM','COM',174,'ISO 3166-2:KM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Congo','CG','COG',178,'ISO 3166-2:CG');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Congo, the Democratic Republic of the','CD','COD',180,'ISO 3166-2:CD');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Cook Islands','CK','COK',184,'ISO 3166-2:CK');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Costa Rica','CR','CRI',188,'ISO 3166-2:CR');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Côte d''Ivoire','CI','CIV',384,'ISO 3166-2:CI');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Croatia','HR','HRV',191,'ISO 3166-2:HR');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Cuba','CU','CUB',192,'ISO 3166-2:CU');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Cyprus','CY','CYP',196,'ISO 3166-2:CY');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Czech Republic','CZ','CZE',203,'ISO 3166-2:CZ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Denmark','DK','DNK',208,'ISO 3166-2:DK');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Djibouti','DJ','DJI',262,'ISO 3166-2:DJ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Dominica','DM','DMA',212,'ISO 3166-2:DM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Dominican Republic','DO','DOM',214,'ISO 3166-2:DO');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Ecuador','EC','ECU',218,'ISO 3166-2:EC');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Egypt','EG','EGY',818,'ISO 3166-2:EG');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('El Salvador','SV','SLV',222,'ISO 3166-2:SV');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Equatorial Guinea','GQ','GNQ',226,'ISO 3166-2:GQ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Eritrea','ER','ERI',232,'ISO 3166-2:ER');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Estonia','EE','EST',233,'ISO 3166-2:EE');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Ethiopia','ET','ETH',231,'ISO 3166-2:ET');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Falkland Islands (Malvinas)','FK','FLK',238,'ISO 3166-2:FK');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Faroe Islands','FO','FRO',234,'ISO 3166-2:FO');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Fiji','FJ','FJI',242,'ISO 3166-2:FJ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Finland','FI','FIN',246,'ISO 3166-2:FI');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('France','FR','FRA',250,'ISO 3166-2:FR');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('French Guiana','GF','GUF',254,'ISO 3166-2:GF');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('French Polynesia','PF','PYF',258,'ISO 3166-2:PF');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('French Southern Territories','TF','ATF',260,'ISO 3166-2:TF');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Gabon','GA','GAB',266,'ISO 3166-2:GA');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Gambia','GM','GMB',270,'ISO 3166-2:GM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Georgia','GE','GEO',268,'ISO 3166-2:GE');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Germany','DE','DEU',276,'ISO 3166-2:DE');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Ghana','GH','GHA',288,'ISO 3166-2:GH');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Gibraltar','GI','GIB',292,'ISO 3166-2:GI');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Greece','GR','GRC',300,'ISO 3166-2:GR');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Greenland','GL','GRL',304,'ISO 3166-2:GL');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Grenada','GD','GRD',308,'ISO 3166-2:GD');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Guadeloupe','GP','GLP',312,'ISO 3166-2:GP');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Guam','GU','GUM',316,'ISO 3166-2:GU');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Guatemala','GT','GTM',320,'ISO 3166-2:GT');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Guernsey','GG','GGY',831,'ISO 3166-2:GG');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Guinea','GN','GIN',324,'ISO 3166-2:GN');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Guinea-Bissau','GW','GNB',624,'ISO 3166-2:GW');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Guyana','GY','GUY',328,'ISO 3166-2:GY');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Haiti','HT','HTI',332,'ISO 3166-2:HT');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Heard Island and McDonald Islands','HM','HMD',334,'ISO 3166-2:HM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Holy See (Vatican City State)','VA','VAT',336,'ISO 3166-2:VA');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Honduras','HN','HND',340,'ISO 3166-2:HN');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Hong Kong','HK','HKG',344,'ISO 3166-2:HK');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Hungary','HU','HUN',348,'ISO 3166-2:HU');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Iceland','IS','ISL',352,'ISO 3166-2:IS');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('India','IN','IND',356,'ISO 3166-2:IN');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Indonesia','ID','IDN',360,'ISO 3166-2:ID');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Iran, Islamic Republic of','IR','IRN',364,'ISO 3166-2:IR');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Iraq','IQ','IRQ',368,'ISO 3166-2:IQ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Ireland','IE','IRL',372,'ISO 3166-2:IE');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Isle of Man','IM','IMN',833,'ISO 3166-2:IM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Israel','IL','ISR',376,'ISO 3166-2:IL');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Italy','IT','ITA',380,'ISO 3166-2:IT');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Jamaica','JM','JAM',388,'ISO 3166-2:JM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Japan','JP','JPN',392,'ISO 3166-2:JP');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Jersey','JE','JEY',832,'ISO 3166-2:JE');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Jordan','JO','JOR',400,'ISO 3166-2:JO');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Kazakhstan','KZ','KAZ',398,'ISO 3166-2:KZ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Kenya','KE','KEN',404,'ISO 3166-2:KE');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Kiribati','KI','KIR',296,'ISO 3166-2:KI');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Korea, Democratic People''s Republic of','KP','PRK',408,'ISO 3166-2:KP');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Korea, Republic of','KR','KOR',410,'ISO 3166-2:KR');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Kuwait','KW','KWT',414,'ISO 3166-2:KW');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Kyrgyzstan','KG','KGZ',417,'ISO 3166-2:KG');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Lao People''s Democratic Republic','LA','LAO',418,'ISO 3166-2:LA');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Latvia','LV','LVA',428,'ISO 3166-2:LV');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Lebanon','LB','LBN',422,'ISO 3166-2:LB');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Lesotho','LS','LSO',426,'ISO 3166-2:LS');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Liberia','LR','LBR',430,'ISO 3166-2:LR');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Libyan Arab Jamahiriya','LY','LBY',434,'ISO 3166-2:LY');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Liechtenstein','LI','LIE',438,'ISO 3166-2:LI');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Lithuania','LT','LTU',440,'ISO 3166-2:LT');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Luxembourg','LU','LUX',442,'ISO 3166-2:LU');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Macao','MO','MAC',446,'ISO 3166-2:MO');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Macedonia, the former Yugoslav Republic of','MK','MKD',807,'ISO 3166-2:MK');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Madagascar','MG','MDG',450,'ISO 3166-2:MG');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Malawi','MW','MWI',454,'ISO 3166-2:MW');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Malaysia','MY','MYS',458,'ISO 3166-2:MY');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Maldives','MV','MDV',462,'ISO 3166-2:MV');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Mali','ML','MLI',466,'ISO 3166-2:ML');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Malta','MT','MLT',470,'ISO 3166-2:MT');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Marshall Islands','MH','MHL',584,'ISO 3166-2:MH');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Martinique','MQ','MTQ',474,'ISO 3166-2:MQ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Mauritania','MR','MRT',478,'ISO 3166-2:MR');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Mauritius','MU','MUS',480,'ISO 3166-2:MU');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Mayotte','YT','MYT',175,'ISO 3166-2:YT');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Mexico','MX','MEX',484,'ISO 3166-2:MX');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Micronesia, Federated States of','FM','FSM',583,'ISO 3166-2:FM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Moldova, Republic of','MD','MDA',498,'ISO 3166-2:MD');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Monaco','MC','MCO',492,'ISO 3166-2:MC');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Mongolia','MN','MNG',496,'ISO 3166-2:MN');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Montenegro','ME','MNE',499,'ISO 3166-2:ME');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Montserrat','MS','MSR',500,'ISO 3166-2:MS');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Morocco','MA','MAR',504,'ISO 3166-2:MA');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Mozambique','MZ','MOZ',508,'ISO 3166-2:MZ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Myanmar','MM','MMR',104,'ISO 3166-2:MM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Namibia','NA','NAM',516,'ISO 3166-2:NA');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Nauru','NR','NRU',520,'ISO 3166-2:NR');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Nepal','NP','NPL',524,'ISO 3166-2:NP');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Netherlands','NL','NLD',528,'ISO 3166-2:NL');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Netherlands Antilles','AN','ANT',530,'ISO 3166-2:AN');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('New Caledonia','NC','NCL',540,'ISO 3166-2:NC');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('New Zealand','NZ','NZL',554,'ISO 3166-2:NZ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Nicaragua','NI','NIC',558,'ISO 3166-2:NI');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Niger','NE','NER',562,'ISO 3166-2:NE');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Nigeria','NG','NGA',566,'ISO 3166-2:NG');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Niue','NU','NIU',570,'ISO 3166-2:NU');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Norfolk Island','NF','NFK',574,'ISO 3166-2:NF');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Northern Mariana Islands','MP','MNP',580,'ISO 3166-2:MP');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Norway','NO','NOR',578,'ISO 3166-2:NO');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Oman','OM','OMN',512,'ISO 3166-2:OM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Pakistan','PK','PAK',586,'ISO 3166-2:PK');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Palau','PW','PLW',585,'ISO 3166-2:PW');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Palestinian Territory, Occupied','PS','PSE',275,'ISO 3166-2:PS');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Panama','PA','PAN',591,'ISO 3166-2:PA');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Papua New Guinea','PG','PNG',598,'ISO 3166-2:PG');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Paraguay','PY','PRY',600,'ISO 3166-2:PY');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Peru','PE','PER',604,'ISO 3166-2:PE');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Philippines','PH','PHL',608,'ISO 3166-2:PH');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Pitcairn','PN','PCN',612,'ISO 3166-2:PN');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Poland','PL','POL',616,'ISO 3166-2:PL');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Portugal','PT','PRT',620,'ISO 3166-2:PT');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Puerto Rico','PR','PRI',630,'ISO 3166-2:PR');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Qatar','QA','QAT',634,'ISO 3166-2:QA');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Réunion','RE','REU',638,'ISO 3166-2:RE');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Romania','RO','ROU',642,'ISO 3166-2:RO');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Russian Federation','RU','RUS',643,'ISO 3166-2:RU');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Rwanda','RW','RWA',646,'ISO 3166-2:RW');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Saint Barthélemy','BL','BLM',652,'ISO 3166-2:BL');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Saint Helena, Ascension and Tristan da Cunha','SH','SHN',654,'ISO 3166-2:SH');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Saint Kitts and Nevis','KN','KNA',659,'ISO 3166-2:KN');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Saint Lucia','LC','LCA',662,'ISO 3166-2:LC');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Saint Martin (French part)','MF','MAF',663,'ISO 3166-2:MF');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Saint Pierre and Miquelon','PM','SPM',666,'ISO 3166-2:PM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Saint Vincent and the Grenadines','VC','VCT',670,'ISO 3166-2:VC');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Samoa','WS','WSM',882,'ISO 3166-2:WS');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('San Marino','SM','SMR',674,'ISO 3166-2:SM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Sao Tome and Principe','ST','STP',678,'ISO 3166-2:ST');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Saudi Arabia','SA','SAU',682,'ISO 3166-2:SA');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Senegal','SN','SEN',686,'ISO 3166-2:SN');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Serbia','RS','SRB',688,'ISO 3166-2:RS');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Seychelles','SC','SYC',690,'ISO 3166-2:SC');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Sierra Leone','SL','SLE',694,'ISO 3166-2:SL');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Singapore','SG','SGP',702,'ISO 3166-2:SG');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Slovakia','SK','SVK',703,'ISO 3166-2:SK');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Slovenia','SI','SVN',705,'ISO 3166-2:SI');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Solomon Islands','SB','SLB',090,'ISO 3166-2:SB');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Somalia','SO','SOM',706,'ISO 3166-2:SO');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('South Africa','ZA','ZAF',710,'ISO 3166-2:ZA');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('South Georgia and the South Sandwich Islands','GS','SGS',239,'ISO 3166-2:GS');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Spain','ES','ESP',724,'ISO 3166-2:ES');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Sri Lanka','LK','LKA',144,'ISO 3166-2:LK');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Sudan','SD','SDN',736,'ISO 3166-2:SD');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Suriname','SR','SUR',740,'ISO 3166-2:SR');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Svalbard and Jan Mayen','SJ','SJM',744,'ISO 3166-2:SJ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Swaziland','SZ','SWZ',748,'ISO 3166-2:SZ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Sweden','SE','SWE',752,'ISO 3166-2:SE');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Switzerland','CH','CHE',756,'ISO 3166-2:CH');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Syrian Arab Republic','SY','SYR',760,'ISO 3166-2:SY');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Taiwan, Province of China','TW','TWN',158,'ISO 3166-2:TW');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Tajikistan','TJ','TJK',762,'ISO 3166-2:TJ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Tanzania, United Republic of','TZ','TZA',834,'ISO 3166-2:TZ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Thailand','TH','THA',764,'ISO 3166-2:TH');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Timor-Leste','TL','TLS',626,'ISO 3166-2:TL');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Togo','TG','TGO',768,'ISO 3166-2:TG');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Tokelau','TK','TKL',772,'ISO 3166-2:TK');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Tonga','TO','TON',776,'ISO 3166-2:TO');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Trinidad and Tobago','TT','TTO',780,'ISO 3166-2:TT');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Tunisia','TN','TUN',788,'ISO 3166-2:TN');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Turkey','TR','TUR',792,'ISO 3166-2:TR');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Turkmenistan','TM','TKM',795,'ISO 3166-2:TM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Turks and Caicos Islands','TC','TCA',796,'ISO 3166-2:TC');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Tuvalu','TV','TUV',798,'ISO 3166-2:TV');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Uganda','UG','UGA',800,'ISO 3166-2:UG');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Ukraine','UA','UKR',804,'ISO 3166-2:UA');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('United Arab Emirates','AE','ARE',784,'ISO 3166-2:AE');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('United Kingdom','GB','GBR',826,'ISO 3166-2:GB');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('United States','US','USA',840,'ISO 3166-2:US');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('United States Minor Outlying Islands','UM','UMI',581,'ISO 3166-2:UM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Uruguay','UY','URY',858,'ISO 3166-2:UY');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Uzbekistan','UZ','UZB',860,'ISO 3166-2:UZ');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Vanuatu','VU','VUT',548,'ISO 3166-2:VU');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Venezuela, Bolivarian Republic of','VE','VEN',862,'ISO 3166-2:VE');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Viet Nam','VN','VNM',704,'ISO 3166-2:VN');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Virgin Islands, British','VG','VGB',092,'ISO 3166-2:VG');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Virgin Islands, U.S.','VI','VIR',850,'ISO 3166-2:VI');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Wallis and Futuna','WF','WLF',876,'ISO 3166-2:WF');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Western Sahara','EH','ESH',732,'ISO 3166-2:EH');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Yemen','YE','YEM',887,'ISO 3166-2:YE');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Zambia','ZM','ZMB',894,'ISO 3166-2:ZM');
INSERT INTO Countries(Name,Alpha2,Alpha3,NumericCode,Iso) VALUES ('Zimbabwe','ZW','ZWE',716,'ISO 3166-2:ZW');
